mysql:
  image: mysql:5.7.14
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=$$3cureUS
    - MYSQL_DATABASE=cs4501
    - MYSQL_USER=www
    - MYSQL_PASSWORD=$$3cureUS
  expose:
    - "3306"
  volumes:
    - ./microservices/init_test_db.sh:/docker-entrypoint-initdb.d/init_test_db.sh

models:
    container_name: models
    image: tp33/django
    restart: always
    external_links:
      -  mysql:db
    volumes:
      - ./microservices:/app
    expose:
      - "8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/services/wsgi.py"

exp:
   container_name: exp
   image: tp33/django
   restart: always
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   expose:
      - "8000"
   volumes:
      - ./experience:/app
   command: "mod_wsgi-express start-server --reload-on-changes /app/experience/wsgi.py"

web:
   image: tp33/django
   container_name: web
   restart: always
   links:
      - exp:exp-api
   expose:
      - "8000"
   volumes:
      - ./web_layer:/app
   command: "mod_wsgi-express start-server --reload-on-changes /app/web_layer/wsgi.py"

web1:
   image: tp33/django
   container_name: web1
   restart: always
   links:
      - exp:exp-api
   expose:
      - "8000"
   volumes:
      - ./web_layer:/app
   command: "mod_wsgi-express start-server --reload-on-changes /app/web_layer/wsgi.py"

nginx:
  image: nginx
  ports:
    - "80:80"
  expose:
    - "80"
  links:
    - web
    - web1
  volumes:
    - ./nginx:/etc/nginx

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      TOPICS: new-listings-topic, pageview-topic
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   expose:
      - "9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/script
   command: "python /script/script.py"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.11.0 && sleep 10 && python /app/selenium_tests.py && tail -f /dev/null"

spark_batch:
   image: tp33/django
   container_name: spark_batch
   links:
      - kafka:kafka
   volumes:
      - ./spark:/app
   command: "python /app/pageview_script.py"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./spark:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./spark:/tmp/data
