models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./microservices:/app
    expose:
      - "8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/services/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   expose:
      - "8000"
   volumes:
      - ./experience:/app
   command: "mod_wsgi-express start-server --reload-on-changes /app/experience/wsgi.py"



web:
   image: tp33/django
   links:
      - exp:exp-api
   expose:
      - "8000"
   volumes:
      - ./web_layer:/app
   command: "mod_wsgi-express start-server --reload-on-changes /app/web_layer/wsgi.py"

web1:
   image: tp33/django
   links:
      - exp:exp-api
   expose:
      - "8000"
   volumes:
      - ./web_layer:/app
   command: "mod_wsgi-express start-server --reload-on-changes /app/web_layer/wsgi.py"

nginx:
  image: nginx
  ports:
    - "80:80"
  expose:
    - "80"
  links:
    - web
    - web1
  volumes:
    - ./nginx:/etc/nginx

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   expose:
      - "9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/script
   command: "python /script/script.py"
